spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/fitness-micro-user
#    username: postgres
#    password: PostGres123
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#  jackson:
#    date-format: dd-MM-yyyy
#
#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: false
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#
#server:
#  port: 8081
#
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE